### ISSUE TITLE
Дублирование символов

### ISSUE THREAD

**Issue by dzeveloper** [ssilver2007/LCD_1602_RUS#2]
Есть вот такой скетч:
```
#include <LCD_1602_RUS.h>

LCD_1602_RUS lcd(63, 16, 2);

void setup()
{
  lcd.init();
  lcd.backlight();
  lcd.print(L"абвгдеёжзийклмно");
}

void loop()
{
}

```

После выполнения на экране:
`айклменжзийклмно`
[Фото](https://cloud.githubusercontent.com/assets/18378985/22865498/c7202958-f176-11e6-860c-43c6d0a06b27.jpg)

**Comment by ssilver2007** [comment]
Все верно, так и должно быть.

12 февраля 2017 г., 22:53 пользователь Kanris826 <notifications@github.com>
написал:

**Comment by dzeveloper** [comment]
Вы имеете в виду, что если символы отображаются не в своих позициях, то это нормально?

**Comment by ssilver2007** [comment]
Я считаю нормальным сначала прочитать описание библиотеки, прежде чем
задавать вопросы.

13 февр. 2017 г. 15:03 пользователь "Kanris826" <notifications@github.com>
написал:

**Comment by UUSR** [comment]
@Kanris826 @ssilver2007 хочу немного уточнить ,по поводу максимального количества символов.
Без проблем выводится максимум десять символов кириллицы.
![img_0228](https://cloud.githubusercontent.com/assets/17599033/23106546/7a4a571a-f6ef-11e6-9049-3198ea25ae6c.jpg)

**Comment by ssilver2007** [comment]
В строке "абвгдеёжзи" как раз 8 уникальных кириллических символа.
Попробуйте вывести на LCD строку "бвгдёжзикл" и все встанет на свои места.

20 февраля 2017 г., 0:06 пользователь UUSR <notifications@github.com>
написал:
